# Generated by Django 6.1.1 on 2026-09-15 15:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_clientfollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorAccount',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='moderator_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('permissions', models.JSONField(default=dict)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('is_senior', models.BooleanField(default=False)),
                ('actions_taken', models.IntegerField(default=0)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moderator Account',
                'verbose_name_plural': 'Moderator Accounts',
                'indexes': [models.Index(fields=['department'], name='account_mod_departm_95b2f6_idx'), models.Index(fields=['is_senior'], name='account_mod_is_seni_56ed6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.CharField(blank=True, max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('credits_earned', models.IntegerField(default=0)),
                ('notification_email', models.BooleanField(default=True)),
                ('notification_push', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Account',
                'verbose_name_plural': 'Student Accounts',
                'indexes': [models.Index(fields=['grade_level'], name='account_stu_grade_l_2cb8b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAccount',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_account_id', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('total_students', models.IntegerField(default=0)),
                ('total_courses', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('auto_payout', models.BooleanField(default=False)),
                ('payout_schedule', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='monthly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher Account',
                'verbose_name_plural': 'Teacher Accounts',
                'indexes': [models.Index(fields=['rating'], name='account_tea_rating_5cf1aa_idx'), models.Index(fields=['stripe_account_id'], name='account_tea_stripe__242563_idx')],
            },
        ),
    ]
