# Generated by Django 6.1.1 on 2026-09-15 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client', '0002_clientfollow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfollow',
            options={'verbose_name': 'Client Follow', 'verbose_name_plural': 'Client Follows'},
        ),
        migrations.RemoveIndex(
            model_name='clientfollow',
            name='client_clie_followe_cd678a_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='client',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('moderator', 'Moderator')], db_index=True, default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='display_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(error_messages={'unique': 'An account with that email address already exists.'}, max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive accounts cannot log in'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Django admin access'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Email verification status'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['role', 'is_active'], name='client_clie_role_df812f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_verified', 'created_at'], name='client_clie_is_veri_87a957_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['display_name'], name='client_clie_display_d40a77_idx'),
        ),
        migrations.AddIndex(
            model_name='clientfollow',
            index=models.Index(fields=['follower', 'created_at'], name='client_clie_followe_b75f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientfollow',
            index=models.Index(fields=['following', 'created_at'], name='client_clie_followi_5f099e_idx'),
        ),
    ]
