# Generated by Django 6.1.1 on 2026-09-15 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='payment.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payment.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_invoice', to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payment.subscriptionplan'),
        ),
        migrations.AlterUniqueTogether(
            name='webhookevent',
            unique_together={('gateway', 'event_id')},
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'is_active'], name='payment_cou_code_52cde9_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_until'], name='payment_cou_valid_f_cbdde7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='payment_ord_user_id_724e74_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['gateway_order_id'], name='payment_ord_gateway_0f3bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='payment_ord_status_8c5a85_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['transaction', 'status'], name='payment_ref_transac_4d00f1_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['user', 'status'], name='payment_ref_user_id_dc7dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='payment_sub_user_id_b2f654_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_subscription_id'], name='payment_sub_stripe__d0aa4d_idx'),
        ),
    ]
