# Generated by Django 6.1.1 on 2026-09-15 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('condition', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('notify_channels', models.JSONField(default=list)),
                ('cooldown_minutes', models.IntegerField(default=60)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_users', models.ManyToManyField(blank=True, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analytics Settings',
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('rate', 'Rate')], max_length=20)),
                ('app', models.CharField(blank=True, db_index=True, max_length=50)),
                ('user_role', models.CharField(blank=True, db_index=True, max_length=20)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('dimension_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('dimension_value', models.CharField(blank=True, max_length=200)),
                ('count', models.BigIntegerField(default=0)),
                ('sum_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('avg_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('percentiles', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'metric_name'],
                'indexes': [models.Index(fields=['date', 'metric_name'], name='analytic_da_date_4ad73f_idx'), models.Index(fields=['app', 'date'], name='analytic_da_app_07d712_idx')],
                'unique_together': {('date', 'metric_name', 'app', 'user_role', 'country', 'device_type', 'dimension_key', 'dimension_value')},
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('metric_card', 'Metric Card'), ('table', 'Table'), ('funnel', 'Funnel'), ('retention', 'Retention Heatmap'), ('cohort', 'Cohort Analysis'), ('geo_map', 'Geo Map')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metric_names', models.JSONField(default=list)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('time_range', models.JSONField(default=dict)),
                ('granularity', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='day', max_length=10)),
                ('chart_options', models.JSONField(blank=True, default=dict)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6)),
                ('height', models.IntegerField(default=4)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytic.dashboard')),
            ],
            options={
                'ordering': ['y', 'x'],
            },
        ),
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funnel_name', models.CharField(db_index=True, max_length=100)),
                ('step_order', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['funnel_name', 'step_order'],
                'unique_together': {('funnel_name', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='HourlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('app', models.CharField(blank=True, db_index=True, max_length=50)),
                ('count', models.BigIntegerField(default=0)),
                ('sum_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['hour', 'metric_name'], name='analytic_ho_hour_4cfb05_idx')],
                'unique_together': {('hour', 'metric_name', 'app')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], default='json', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('query', models.JSONField(default=dict)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_cron', models.CharField(blank=True, max_length=100)),
                ('schedule_timezone', models.CharField(default='UTC', max_length=50)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='analytics/reports/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('row_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_date', models.DateField(db_index=True)),
                ('cohort_size', models.IntegerField(default=0)),
                ('period', models.IntegerField(default=0)),
                ('period_type', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10)),
                ('retained_users', models.IntegerField(default=0)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('app', models.CharField(blank=True, db_index=True, max_length=50)),
                ('user_role', models.CharField(blank=True, db_index=True, max_length=20)),
                ('acquisition_channel', models.CharField(blank=True, db_index=True, max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cohort_date', 'period'],
                'indexes': [models.Index(fields=['cohort_date', 'period_type'], name='analytic_re_cohort__60cbce_idx')],
                'unique_together': {('cohort_date', 'period', 'period_type', 'app', 'user_role', 'acquisition_channel')},
            },
        ),
        migrations.CreateModel(
            name='AlertTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metric_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='analytic.alert')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['alert', 'triggered_at'], name='analytic_al_alert_i_269709_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user.registered', 'User Registered'), ('user.login', 'User Login'), ('user.logout', 'User Logout'), ('user.verified', 'User Verified'), ('user.deactivated', 'User Deactivated'), ('course.created', 'Course Created'), ('course.published', 'Course Published'), ('course.enrolled', 'Course Enrolled'), ('course.completed', 'Course Completed'), ('course.dropped', 'Course Dropped'), ('lecture.completed', 'Lecture Completed'), ('assessment.started', 'Assessment Started'), ('assessment.submitted', 'Assessment Submitted'), ('assessment.graded', 'Assessment Graded'), ('assessment.passed', 'Assessment Passed'), ('assessment.failed', 'Assessment Failed'), ('payment.initiated', 'Payment Initiated'), ('payment.completed', 'Payment Completed'), ('payment.failed', 'Payment Failed'), ('payment.refunded', 'Payment Refunded'), ('subscription.started', 'Subscription Started'), ('subscription.cancelled', 'Subscription Cancelled'), ('subscription.renewed', 'Subscription Renewed'), ('earning.accrued', 'Earning Accrued'), ('payout.requested', 'Payout Requested'), ('payout.completed', 'Payout Completed'), ('message.sent', 'Message Sent'), ('thread.created', 'Thread Created'), ('post.created', 'Post Created'), ('comment.created', 'Comment Created'), ('like.created', 'Like Created'), ('review.created', 'Review Created'), ('notification.sent', 'Notification Sent'), ('notification.opened', 'Notification Opened'), ('notification.clicked', 'Notification Clicked'), ('error.occurred', 'Error Occurred'), ('api.request', 'API Request'), ('page.view', 'Page View')], db_index=True, max_length=50)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('source_app', models.CharField(blank=True, db_index=True, max_length=50)),
                ('source_version', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='analytic_ev_event_t_ad9de8_idx'), models.Index(fields=['user', 'event_type', 'timestamp'], name='analytic_ev_user_id_75bb32_idx'), models.Index(fields=['source_app', 'event_type', 'timestamp'], name='analytic_ev_source__3502b0_idx')],
            },
        ),
    ]
