# Generated by Django 6.1.1 on 2026-09-15 15:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('client', '0003_alter_clientfollow_options_and_more'),
        ('course', '0001_initial'),
        ('earning', '0001_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('top_up', 'Top Up'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='transaction.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming (Revenue)'), ('outgoing', 'Outgoing (Payout/Expense)')], db_index=True, max_length=10)),
                ('transaction_type', models.CharField(choices=[('course_sale', 'Course Sale'), ('subscription', 'Subscription'), ('bundle_sale', 'Bundle Sale'), ('upgrade', 'Upgrade'), ('donation', 'Donation'), ('refund_received', 'Refund Received'), ('teacher_payout', 'Teacher Payout'), ('platform_fee', 'Platform Fee'), ('refund_issued', 'Refund Issued'), ('adjustment', 'Adjustment'), ('bonus', 'Bonus'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gateway', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay'), ('manual', 'Manual'), ('internal', 'Internal')], max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('gateway_transfer_id', models.CharField(blank=True, max_length=200)),
                ('gateway_payout_id', models.CharField(blank=True, max_length=200)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('revenue_share_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('teacher_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payout_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('wise', 'Wise')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('billing_country', models.CharField(blank=True, max_length=2)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='assessment.attempt')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.bundle')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_transactions', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_transactions', to='payment.coupon')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='course.course')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='course.enrollment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_transactions', to='payment.order')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_transactions', to='earning.payout')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.subscription')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'direction', 'status'], name='transaction_user_id_fc2f10_idx'), models.Index(fields=['teacher', 'direction', 'status'], name='transaction_teacher_695dbe_idx'), models.Index(fields=['course', 'direction'], name='transaction_course__3cfc23_idx'), models.Index(fields=['transaction_type', 'status'], name='transaction_transac_dd72b0_idx'), models.Index(fields=['gateway_transaction_id'], name='transaction_gateway_c2896a_idx'), models.Index(fields=['created_at'], name='transaction_created_0b821d_idx')],
            },
        ),
    ]
