# Generated by Django 6.1.1 on 2026-09-15 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('earning', '0001_initial'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='earning_payouts', to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='revenuereport',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacherearning',
            index=models.Index(fields=['pending_payout'], name='earning_tea_pending_92886a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherearning',
            index=models.Index(fields=['stripe_onboarding_complete'], name='earning_tea_stripe__8b3ca1_idx'),
        ),
        migrations.AddField(
            model_name='payout',
            name='earning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='earning.teacherearning'),
        ),
        migrations.AddIndex(
            model_name='revenuereport',
            index=models.Index(fields=['teacher', 'period_start'], name='earning_rev_teacher_fc2f64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revenuereport',
            unique_together={('teacher', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['teacher', 'status'], name='earning_pay_teacher_b70691_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'requested_at'], name='earning_pay_status_780a1e_idx'),
        ),
    ]
